### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by halilertekin** [marbemac/ralph#1]
Errors prevented startup:

While building the application:
error: no such package: 'hammer'
error: no such package: 'iron-router'
error: no such package: 'percolatestudio-migrations'
error: no such package: 'npm'
error: no such package: 'stylus-latest'
error: no such package: 'kadira'
error: no such package: 'segment.io'

**Comment by marbemac** [comment]
Ah interesting, my guess is that the old packaging system is being phased out after the 0.9 update. I'll take a look at this, and update Ralph to 0.9.4 in the process.

**Comment by halilertekin** [comment]
> Meteor 0.9.2.2 is available. Update this project with 'meteor update'.
> => Started MongoDB.
> => Errors prevented startup:

While building the application:
error: no such package: 'hammer'
error: no such package: 'iron-router'
error: no such package: 'percolatestudio-migrations'
error: no such package: 'npm'
error: no such package: 'stylus-latest'
error: no such package: 'kadira'
error: no such package: 'segment.io'

=> Your application has errors. Waiting for file change.

I'm getting such an error ,Although water is the most current that does not work. In the waiting room there is a muscle studies.I tested the phone THAT iPhone 5s, but there are serious problems .

**Comment by marbemac** [comment]
I've updated Ralph to support Meteor 0.9.4, everything should work OK now!
