### ISSUE TITLE
Update the Ralph chat app and write a blog-post or tutorial?

### ISSUE THREAD

**Issue by dalerka** [marbemac/ralph#4]
Hi, 
First of all, thank you for opensourcing your work - I've learned quite a few things!
I wonder if there's any chance you could update/refactor this app in view of some best practices, packages and approaches (regarding security, animations, user profiles, access to camera and uploads etc.) for building apps with Meteor in 2015?

Also I'd highly appreciate if you could put more _comments_ in the code and perhaps write a blog post about building, rethinking and re-bulding a meteor-based chat app?

Thanks again! 

p.s.: I'd prefer to see this in JavaScript, but I understand asking you to port this to JS would be too much. :)

**Comment by marbemac** [comment]
Hi @dalerka, I'm glad you've found Ralph useful! Unfortunately I have a separate full time job now and simply don't have the time to do what you're describing. Perhaps later this year I will have the time, but for now I'm closing this issue. Thanks again for the interest.

**Comment by dalerka** [comment]
@marbemac , I see, no worries, thanks anyway!
